apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .env: REFUQUJBU0VfVVJMPXBvc3RyZ3JlczovL3Bvc3RncmVzOnBvc3RncmVzQGxvY2FsaG9zdGlua3ViZXJlbnRlczo1NDMyCkNBVENIX1NJWkU9MTAKUEFZTUVOVF9HQVRFV0FZX1VSTD1hcGkucmF6b3JwYXkuY29tCk1BWF9DQVJUX0lURU1TPTIwClNFU1NJX1RJTUVPVVQ9MzYwMA==
